ALTER TABLE "User"
ADD COLUMN "nombre" TEXT NOT NULL DEFAULT 'Admin',
ADD COLUMN "apellido" TEXT NOT NULL DEFAULT 'Sistema';

ALTER TABLE "User"
ALTER COLUMN "nombre" DROP DEFAULT,
ALTER COLUMN "apellido" DROP DEFAULT;
